* ### Numerical Python 今天可是星期五耶，就少学一点吧，不资道为什莫打简介有点台湾强唉，可能是老师的课听多了8 别忘了import numpy as np刻在dna里哦

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2# numpy会快很多
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 25.9 ms
Wall time: 1.07 s


* # 4.1多维数组对象 Numpy ndarray

In [11]:
import numpy as np
data = np.random.randn(2, 3)#rand函数是[0，1)内随机取数
data

array([[-0.10618567,  0.15765506,  0.68348063],
       [ 0.93735085, -0.55677976,  0.94239549]])

In [8]:
data * 10

array([[-7.20079767,  9.60545317, -8.4056729 ],
       [-3.21015837, -7.92093455, -3.20007809]])

In [12]:
data + data

array([[-0.21237135,  0.31531012,  1.36696126],
       [ 1.87470171, -1.11355953,  1.88479097]])

In [13]:
data.shape

(2, 3)

* # 4.1.1生成ndarray

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)#化为阵列
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr1.ndim

1

In [18]:
arr2.ndim#数组维度

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype
#数据类型

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))# 2个3*2矩阵

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* # 4.1.2ndarray的数据结构

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([-1.2, 2.5, 3.7, -4.3, 5.9])
arr.dtype

dtype('float64')

In [41]:
arr.astype(np.int32)#转为整数，小数部分直接被去掉

array([-1,  2,  3, -4,  5])

In [43]:
arr3 =np.array(['1.25', '-9.6', '42'], dtype=np.string_)
arr3.astype(float)
#字符串转数字

array([ 1.25, -9.6 , 42.  ])

In [44]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)#astype成calibers的type

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# * 4.1.3numpy数组算术

In [46]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

* # 4.1.4基本索引与切片

arr = np.arange(10)
arr

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [61]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [62]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    64, 12345,    64,     8,
           9])

In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0,2]

3

In [66]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d.shape

(2, 2, 3)

* # 4.1.4.1 数组的切片索引 (索引降维，切片不降维！)

In [71]:
arr[6]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [72]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [73]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr2d[:2,2]#都有冒号才不降维

array([3, 6])

In [82]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [86]:
arr2d[:, 1]#都有冒号才不降维

array([2, 5, 8])

In [76]:
arr2d[2]

array([7, 8, 9])

In [77]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [87]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])