### 要考免疫了，加上一堆事还有自己摆烂（嘻嘻）今天把chapter5结束一下吧
### 5.2节的大部分内容啦 索引 排名排序 重复标签 + 5.3

# 5.2.5 算术和数据对齐

In [1]:
import pandas as pd
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [2]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [3]:
s1 + s2
# 找不到就missing

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [5]:
import numpy as np
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [6]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [7]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

# 5.2.5.1 用填充值的算术方法

In [8]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [9]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [10]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [11]:
df1.add(df2, fill_value=0)
# 将0补入missing处（不补两个NaN相加）

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [12]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

# 5.2.5.2 DataFrame和Series间的操作

In [13]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
arr[0]

array([0., 1., 2., 3.])

In [15]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [16]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [17]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [18]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [19]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [20]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [21]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# 5.2.6 函数应用和映射

In [22]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.826743 -0.124202  0.329389
Ohio   -0.079378  1.738144 -0.776053
Texas  -0.880388  1.106065  1.315390
Oregon -0.900430  0.500841  0.455314

In [23]:
np.abs(frame)

b         d         e
Utah    0.826743  0.124202  0.329389
Ohio    0.079378  1.738144  0.776053
Texas   0.880388  1.106065  1.315390
Oregon  0.900430  0.500841  0.455314

In [24]:
f = lambda x: x.max() - x.min()# lambda匿名函数
# 纵轴中最大减最小

In [25]:
frame.apply(f)

b    0.821052
d    1.862346
e    2.091444
dtype: float64

In [26]:
frame.apply(f, axis='columns')
# 固定列就是对行操作

Utah      1.156133
Ohio      2.514198
Texas     2.195778
Oregon    1.401271
dtype: float64

In [27]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)
# 未说明就是axis=0 固定x对y操作

b         d         e
min -0.900430 -0.124202 -0.776053
max -0.079378  1.738144  1.315390

In [28]:
format = lambda x: '%.2f' % x
frame.applymap(format)
# 取两位小数

b      d      e
Utah    -0.83  -0.12   0.33
Ohio    -0.08   1.74  -0.78
Texas   -0.88   1.11   1.32
Oregon  -0.90   0.50   0.46

In [29]:
frame['e'].map(format)

Utah       0.33
Ohio      -0.78
Texas      1.32
Oregon     0.46
Name: e, dtype: object

# 5.2.7 排序和排名

In [30]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [31]:
obj.sort_index()
# 按照index排序

a    1
b    2
c    3
d    0
dtype: int64

In [32]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [33]:
frame.sort_index()
# 默认axis即y即纵轴排序

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [34]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [35]:
frame.sort_index(axis=1, ascending=False)
# ascending=False即倒序排列

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [37]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [38]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [40]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
# missing value会被排序到尾部

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [41]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [42]:
frame.sort_values(by='b')
# 按b来排

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [44]:
frame.sort_values(by=['a', 'b'])
# 多原则排序（先a再b）

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [46]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [47]:
obj.rank()
# 排名赋分，越高越大

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [48]:
obj.rank(method='first')
# 谁先被看到先给谁名次

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [49]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [51]:
frame = pd.DataFrame({ 'a': [0, 1, 0, 1],'b': [4.3, 7, -3, 2],
                      'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [52]:
frame.rank(axis='columns')
# 对行来排名

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [54]:
frame.rank()
# 默认axis=0对y列排序并且默认average

a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0

# 5.2.8 含有重复标签的轴索引

In [55]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [56]:
obj.index.is_unique

False

In [57]:
obj['a']

a    0
a    1
dtype: int64

In [58]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.187875  0.480309 -0.770296
a  0.346476 -0.715732  0.906834
b -0.978860  1.320544  0.209267
b  1.873572  0.151718  1.297743

In [59]:
df.loc['b']

0         1         2
b -0.978860  1.320544  0.209267
b  1.873572  0.151718  1.297743

# 5.3 描述性统计的概述与计算

In [61]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [62]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [64]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [65]:
df.mean(axis='columns', skipna=False)
# 这样就不可以跳过NaN了哦

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [66]:
df.idxmax()

one    b
two    d
dtype: object

In [67]:
df.cumsum()
# 累加

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [68]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [69]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

# 5.3.1 相关性和协方差

In [ ]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')
# 没有下材料就没用了捏

In [ ]:
import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

all_data

In [ ]:
price = pd.DataFrame({ticker: data['Adj Close'] 
                      for ticker, data in all_data.items()})
price

In [ ]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})
volume

In [ ]:
returns = price.pct_change()
returns.tail()
# 后面都是用这些资料进行统计运算啦，就不写了

# 5.3.2 唯一值、计数和成员属性

In [73]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [74]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [75]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [76]:
pd.value_counts(obj.values, sort=False)

a    3
b    2
c    3
d    1
dtype: int64

In [78]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [79]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [80]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])# c,b,a赋值0，1，2
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [81]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [82]:
result = data.apply(pd.value_counts).fillna(0)# 每个数字出现次数
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0